---
title: "Hindcast summary and different forecast scenario for Faroes TAC"
author: "WGNAS 2021 - Life Cycle Model Output"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  word_document:
    reference_docx: template.docx
---

```{r global_options,include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE,fig.width=10,fig.height=10,bg="transparent")
```

```{r,results = 'asis'}
content_df <- data.frame("Section" = 1:17, "Country" = country17Full, "Page" = 2:18)
flextable::flextable(content_df, cwidth = 2, cheight = 0.2) %>%
  flextable::theme_zebra() %>%
  # flextable::fontsize(., size = 11) %>% 
  flextable::padding(., padding.top = 0, padding.bottom = 0)
```


\newpage
```{r,results = 'asis'}
  thispalette <- rev(colorRampPalette(brewer.pal(4,"RdYlBu"))((length(scenario_name)+1)/2))
  this_scenario <- 1
out <- NULL
# for(thisSU in 1:length(regions25)){
for(thiscountry in 1:length(country17)){
      out = c(out, knitr::knit_child("7_Summary_country_FAR_forecast_child.Rmd", quiet = TRUE))
}
cat(out, sep = '\n')

```

