---
title: "Hindcast summary and default forecast scenario (no TAC in Faroes and West Greenland)"
author: "WGNAS 2021 - Life Cycle Model Output"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  word_document:
    reference_docx: template.docx

---

```{r global_options,include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE,fig.width=10,fig.height=10,bg="transparent")
```

```{r,results = 'asis'}
content_df <- data.frame(
	"Spatial_Scale" = c("Complex Scale", rep("",3), "SU Scale", rep("",25)),
	"Location" = c("",cg3[c(1,3,2)], "",regions25Full), 
	"Page" = c(2, 2:4, 5, 5:29))
flextable::flextable(content_df, cwidth = 2, cheight = 0.2) %>%
  flextable::theme_zebra() %>%
  # flextable::fontsize(., size = 11) %>% 
  flextable::padding(., padding.top = 0, padding.bottom = 0)
```



\newpage

# Complex Scale

## North America

```{r,results = 'asis',fig.width=10,fig.height=10}
g <- readRDS("../../temp_docx/forecast_reg_com_sc_North America.rds")
grid.arrange(g)
```

\newpage

## Northern Europe

```{r,results = 'asis',fig.width=10,fig.height=10}
g <- readRDS("../../temp_docx/forecast_reg_com_sc_Northern Europe.rds")
grid.arrange(g)
```

\newpage

## Southern Europe

```{r,results = 'asis',fig.width=10,fig.height=10}
g <- readRDS("../../temp_docx/forecast_reg_com_sc_Southern Europe.rds")
grid.arrange(g)
```

\newpage

# SU Scale

```{r,results = 'asis'}
  thispalette <- rev(colorRampPalette(brewer.pal(4,"RdYlBu"))((length(scenario_name)+1)/2))
  this_scenario <- 1
out <- NULL
# for(thisSU in 1:length(regions25)){
for(thisSU in 1:25){
      out = c(out, knitr::knit_child("7_Summary_SU_0TAC_forecast_child.Rmd", quiet = TRUE))
}
cat(out, sep = '\n')

```

